<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE application SYSTEM "..\schema\AppNavModel.dtd"> -->
<!DOCTYPE application [
<!-- nl= natural language expression id= unique id -->
<!ELEMENT vsn (major)+>
<!ATTLIST vsn
  xmlns CDATA #FIXED ''
  id CDATA #REQUIRED
  aka CDATA #REQUIRED
  path CDATA #REQUIRED
  nl CDATA #REQUIRED>

<!ELEMENT major (minor*) >
<!ATTLIST major
  id CDATA #REQUIRED
  xmlns CDATA #FIXED ''
  lbl CDATA #REQUIRED
  nl CDATA #REQUIRED>



<!ELEMENT minor (evidence*,(action)*)>
<!ATTLIST minor
  xmlns CDATA #FIXED ''
  id CDATA #REQUIRED
  lbl CDATA #IMPLIED
  nl CDATA #REQUIRED>

<!ELEMENT evidence EMPTY>
<!ATTLIST evidence
  xmlns CDATA #FIXED ''
  nl CDATA #IMPLIED
  type NMTOKEN #REQUIRED>

<!ELEMENT article EMPTY>
<!ATTLIST article
  xmlns CDATA #FIXED ''
  nl CDATA #IMPLIED
  lbl CDATA #IMPLIED
  id CDATA #REQUIRED
  type NMTOKEN #REQUIRED>

<!ELEMENT action (article*,evidence*)>
<!ATTLIST action
  xmlns CDATA #FIXED ''
  id ID #REQUIRED
  lbl CDATA #REQUIRED
  nl CDATA #REQUIRED
  type NMTOKEN #IMPLIED>
  
]>

<!-- action type c = critical publication, type t = tactical publication 
in the role of _ in humanity, doing _ 
The LeafyCampus Forum for Scholarship and Exploration

LC - reviving cartesian science
=========================
motivation -> Scepticism, past works inspirations
exposition -> how scholastic science exists and how postmodernity/modernity is a cancelling out
adaptation -> real life design recommendations, criticism, collaborations
campus -> the limitations of formalism, open exploratory activities, campus before concept.
	
				  
				 Study			>
				 
				 Exposition - both critical (post linguistics, occam razor, connectionism) and 
				 			theories of computing based on empirical research. publication of empricism of computing, 
				 construction - rules engines, continuously consistnt systems, interactive proof systems, AI applied expert systems particularly in evidence based med
				 existence-scoutn n scholar, architects forums, collaboration boards - AI. universities.
				 reflection - survey and pedagogical work mainly on classicism and cartesian science. Exposition on new angles to look at science,languages, aesthetics
				 
				 
				 One Issue >
				 Architecture as 

-->
<vsn id="root_version_6" nl="Motivation" aka="Leafy Campus Club" path="Minimalism and Science">
	<major id="About" nl="About" lbl="About">
	
		<minor id="about" lbl="ABOUT HOME" nl="about">
			<action type="ess" lbl="Walking Through the Mission" id="about_step_by_step" nl="">
				<article type="ess" id="Places" lbl="On Places"></article>
				<article type="ess" id="Method" nl=""></article>
				<article type="ess" id="Historical Relevance" nl=""></article>
				<article type="ess" id="What is a Modern Decision System" nl=""></article>
			</action>
			<action type="ess" lbl="Conventions" id="conventions" nl="Like Longfellows blacksmith">
				<article type="ess" id="Scout and Scholar" nl=""></article>
				<article type="ess" id="Colloboration" nl=""></article>
			</action>
		</minor>
		<minor id="Contact" lbl="Contact" nl="Contact form"></minor>
	</major>


	<major id="Minimalism" lbl="Minimalism" nl="" >
		<minor id="About_Minimalism" lbl="HOME" nl="minimalism in software architecture" >
			<action id="about_minimalism_maxims" lbl="A Summary" nl="">
				<article type="ess" id="Our Maxims"></article>
				<article type="ess" id="More On Minimalism"></article>
			</action>	
			<action id="more_on_minimalism_architecture" lbl="More on Minimalism" nl="">
				<article type="ess" id="The Idea of Spaces in Architecture"></article>
			</action>
		</minor>
	
	</major>

	<major id="Cartesian Science" lbl="Cartesian Science" nl="" >
		<minor id="Classical_Sciences" lbl="HOME" nl="reviving_classical_sciences" >
			<action id="Cartesian_Sciences" lbl="Science As Promethean" nl="">
				<article type="ess" id="Science as Promethean"></article>
				<article type="ess" id="Remembering Truesdell"></article>
			</action>	
		</minor>
	</major>

	<major id="MetaCriticism" lbl="Meta Criticism" nl="" >
		<minor id="MetaCriticism" lbl="HOME" nl="criticizing contemproary practices" >
			<action id="Simulated_Models" lbl="MetaCriticism of " nl="">
				<article type="ess" id="Criticism on Science and metacriticism"></article>
				
			</action>	
		</minor>
	</major>
	
	
</vsn>