<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE application SYSTEM "..\schema\AppNavModel.dtd"> -->
<!DOCTYPE application [
<!-- nl= natural language expression id= unique id -->
<!ELEMENT vsn (major)+>
<!ATTLIST vsn
  xmlns CDATA #FIXED ''
  id CDATA #REQUIRED
  aka CDATA #REQUIRED
  path CDATA #REQUIRED
  nl CDATA #REQUIRED>

<!ELEMENT major (minor*) >
<!ATTLIST major
  id CDATA #REQUIRED
  xmlns CDATA #FIXED ''
  lbl CDATA #REQUIRED
  nl CDATA #REQUIRED>



<!ELEMENT minor (evidence*,(action)*)>
<!ATTLIST minor
  xmlns CDATA #FIXED ''
  id CDATA #REQUIRED
  lbl CDATA #IMPLIED
  nl CDATA #IMPLIED
  nl CDATA #IMPLIED>

<!ELEMENT evidence EMPTY>
<!ATTLIST evidence
  xmlns CDATA #FIXED ''
  nl CDATA #IMPLIED
  type NMTOKEN #REQUIRED>

<!ELEMENT article EMPTY>
<!ATTLIST article
  xmlns CDATA #FIXED ''
  nl CDATA #IMPLIED
  type NMTOKEN #REQUIRED>

<!ELEMENT action (article*,evidence*)>
<!ATTLIST action
  xmlns CDATA #FIXED ''
  id ID #IMPLIED
  lbl CDATA #IMPLIED
  nl CDATA #REQUIRED  
  type NMTOKEN #IMPLIED>
  
]>
<!-- action type c = critical publication, type t = tactical publication 
in the role of _ in humanity, doing _ 
The LeafyCampus Science and Exploration Club

major->minor>articles
does>domain>action

About > What this is about, its constitution, Motivation

Principles >     SCIENCE>>

					Science as an emancipatory tool
						Science as naturalistic, redemptive, peaceful
						Implicit ontologies (Metaphysics) in science
						
				  EXPLORATION>>
				  
				  Exploration or open domains
				  		Science as Descriptive, cataloguing
				  		Particular reference to Medicine and negative utilitarianism
				  
				  CRITICISM>>
				  
				  Criticism of non epistemological approaches to decision
				  		Regression, Bayesianism, Lagrangian techniques	
				  	
				  Undecidability
				  		Essential Dualism of symbols and sentiment
				  		Recursive Dualism as applied to this organization
		  		
		  		  LINKS>>
		  		  				  
				  More Articles
				  		Cartesian Dualism and Undecidability
				  		Positivism- Vienna Circle
				  		Treatment of science in eastern and western spiritualism
				  
				  		
				  		
Research 		> ML/AI
				  Employing ML/AI as observational techniques
				  Criticism of Information Theory and Control theory approaches
				  
				  FORMAL SYSTEMS
				  Privacy and Explainability
				  Efficacy of Formal Computing Architectures 
				  Formalization of AI/ML approaches
				  
				  
Conventions		> Scout and Scholar
					Research on Core Sciences
					Mathematical principles of Computing
					Conservation activities
					
				  Machine Intelligence Research Collaboration 	
				  
				 Study			> 
				  

-->
<vsn id="root_version_3" nl="About"  aka="Leafy Campus Foundation"
  path="Hall of Science and Exploration">
      <major id="abt" nl="about, motivation" lbl="About" >
                <minor id="abt_what_why" lbl="Who and What" nl="about">
                  <action type="ess" nl="What this is about, its constitution, Motivation"></action>
                </minor>
      </major>
      <major id="Principles" nl="Principles" lbl="Principles" >
      		<minor id="pr_sc" lbl="Science" nl="Science">
                <action id="pr_sc" lbl="Science as an emancipatory tool" nl="Science as an emancipatory tool">
                 <article type="ess" nl="Science as naturalistic, redemptive, peaceful"></article>
                 <article type="ess" nl="Implicit ontologies and Metaphysics in science"></article>
                 </action>
            </minor>
            <minor id="pr_exp" lbl="Exploration" nl="Exploration">
                 <action id="pr_exp" lbl="Exploration or open domains" nl="Exploration or open domains">
                  <article type="ess" nl="Science as Descriptive cataloguing"></article>
                  <article type="ess" nl="Medicine and negative utilitarianism "></article>
                </action>
             </minor>
                 <minor id="pr_crt" lbl="Criticism" nl="Criticism">
                  <action id="pr_crt" lbl="Does decision need its theory" nl="crticism">
                  <article type="ess" nl="Regression, Bayesianism, Lagrangian techniques"></article>
                  <article type="ess" nl="Medicine and negative utilitarianism"></article>
                </action>
                <action id="pr_org" lbl="Undecidability" nl="dualism">
                  <article type="ess" nl="Essential Dualism of symbols and sentiment"></article>
                  <article type="ess" nl="Recursive Dualism as applied to this organization"></article>
                </action>
                <action id="pr_oth" lbl="More Articles" nl="others">
                  <article type="ess" nl="Cartesian Dualism and Undecidability"></article>
                  <article type="ess" nl="Positivism- Vienna Circle"></article>
                  <article type="ess" nl="Treatment of science in eastern and western spiritualism"></article>
                </action>
             </minor>
      </major>
       <major id="Research" nl="Research" lbl="Research" >
      		<minor id="rs_app" lbl="Applied Research" nl="appld research">
                <action id="rs_ai" lbl="ML/AI" nl="ml/ai">
                 <article type="ess" nl="Employing ML/AI as observational techniques"></article>
                 <article type="ess" nl="Criticism of Information Theory and Control theory approaches"></article>
                 </action>
                 <action id="rs_frml" lbl="Applied Incomplete Formal Systems" nl="formal">
                 <article type="ess" nl="Privacy and Explainability"></article>
                 <article type="ess" nl="Efficacy of Formal Computing Architectures"></article>
                 <article type="ess" nl="Formalization of AI/ML approaches"></article>
                 </action>
            </minor>
            	<minor id="rs_the" lbl="Classicism" nl="stdy research">
                <action id="linguistics" lbl="linguistics" nl="linguistics">
                 <article type="ess" nl="Languages and Justice"></article>
                </action>
                 <action id="rs_proof" lbl="Classical Systems theory" nl="info">
                 <article type="ess" nl="Conservation and Systemic Equilibrium"></article>
                 <article type="ess" nl="Relevance of Classical vs Information theory"></article>
                 </action>
            </minor>
      </major>
				  
	 <major id="Conventions" nl="Conventions" lbl="Conventions" >
      		<minor id="cnv_sct" lbl="Scout and Scholar" nl="Scout and Scholar">
                <action id="sct" lbl="Scout and scholar initiative" nl="sct1">
                <article type="ess" nl="Research on Core Sciences"></article>
                <article type="ess" nl="Conservation activities"></article>
                 </action>
             </minor>
              <minor id="cnv_miri" lbl="Machine Intelligence Research Collaboration" nl="MIRIx">   
                 <action id="cnv_miri" lbl="Machine Intelligence Research Collaboration" nl="mirix">
                 </action>
            </minor>
      </major>		  
</vsn>