<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE application SYSTEM "..\schema\AppNavModel.dtd"> -->
<!DOCTYPE application [
<!-- nl= natural language expression id= unique id -->
<!ELEMENT vsn (major)+>
<!ATTLIST vsn
  xmlns CDATA #FIXED ''
  id CDATA #REQUIRED
  aka CDATA #REQUIRED
  path CDATA #REQUIRED
  nl CDATA #REQUIRED>

<!ELEMENT major (minor*) >
<!ATTLIST major
  id CDATA #REQUIRED
  xmlns CDATA #FIXED ''
  lbl CDATA #REQUIRED
  nl CDATA #REQUIRED>



<!ELEMENT minor (evidence*,(action)*)>
<!ATTLIST minor
  xmlns CDATA #FIXED ''
  id CDATA #REQUIRED
  lbl CDATA #IMPLIED
  type NMTOKEN #REQUIRED
  nl CDATA #REQUIRED>

<!ELEMENT evidence EMPTY>
<!ATTLIST evidence
  xmlns CDATA #FIXED ''
  nl CDATA #IMPLIED
  type NMTOKEN #REQUIRED>

<!ELEMENT article EMPTY>
<!ATTLIST article
  xmlns CDATA #FIXED ''
  nl CDATA #IMPLIED
  id CDATA #REQUIRED
  type NMTOKEN #REQUIRED>

<!ELEMENT action (article*,evidence*)>
<!ATTLIST action
  xmlns CDATA #FIXED ''
  id ID #REQUIRED
  lbl CDATA #REQUIRED
  nl CDATA #REQUIRED
  type NMTOKEN #REQUIRED>
  
]>


<!-- action type c = critical publication, type t = tactical publication 
in the role of _ in humanity, doing _ 
The LeafyCampus Forum for Scholarship and Exploration

LC - reviving cartesian science
=========================
motivation -> Scepticism, past works inspirations
exposition -> how scholastic science exists and how postmodernity/modernity is a cancelling out
adaptation -> real life design recommendations, criticism, collaborations
campus -> the limitations of formalism, open exploratory activities, campus before concept.
	
				  
				 Study			>
				 
				 Exposition - both critical (post linguistics, occam razor, connectionism) and 
				 			theories of computing based on empirical research. publication of empricism of computing, 
				 construction - rules engines, continuously consistnt systems, interactive proof systems, AI applied expert systems particularly in evidence based med
				 existence-scoutn n scholar, architects forums, collaboration boards - AI. universities.
				 reflection - survey and pedagogical work mainly on classicism and cartesian science. Exposition on new angles to look at science,languages, aesthetics
				 
				 
				 One Issue >
				 Architecture as 

-->
<vsn id="root_version_1" nl="Motivation" aka="Manifold" path="Resource Page on Insights on AI">
	<major id="About" nl="About" lbl="About">
		<minor id="about" lbl="ABOUT HOME" nl="about" type="liv">
			<action type="ess" lbl="Subject Matter" id="about_step_by_step" nl="">
				<article type="ess" id="Why-strategeists-should-worry-about-ai" nl=""></article>
				<article type="ess" id="Whitepaper-on-AI-for-capital-intensive-industries" nl=""></article>
			</action>
			<action type="ess" lbl="Who we are" id="whoweare" nl="">
				<article type="ess" id="Who are we" nl=""></article>
			</action>
			<action type="ess" lbl="Write to Us" id="contact" nl="">
				<article type="ess" id="Interaction" nl=""></article>
			</action>
		</minor>
		</major>
		<major id="Issues" nl="Issues" lbl="Issues">
		<minor id="May 25" lbl="May 25" nl="issues" type="liv">
			<action type="ess" lbl="Contents" id="issue_may_25-contents" nl="">
				<article type="ess" id="Agile-as-a-study-in-the-absurd" nl=""></article>
			</action>
		</minor>
	</major>


	
	
	

	<major id="links" lbl="Perma Links" nl="" >
		<minor id="Classical_Sciences" lbl="HOME" nl="reviving_classical_sciences" type="liv">
		
		</minor>
	</major>

	
	
	
</vsn>
